services:
  radarr:
    container_name: radarr
    image: lscr.io/linuxserver/radarr:5.17.2
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      default:
        ipv4_address: ${RADARR_IP}
      downloads:
      t3_proxy:
    volumes:
      - ${DOCKERDIR}/appdata/radarr:/config
      - ${DATADIR_MEDIA}:/data/media
      - ${DATADIR_DOWNLOADS}:/data/downloads
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr-rtr.entrypoints=websecure
      - traefik.http.routers.radarr-rtr.rule=Host(`${RADARR_SUBDOMAIN}.${DOMAINNAME_1}`)
      - traefik.http.routers.radarr-rtr.middlewares=chain-authelia@file
      - traefik.http.routers.radarr-rtr.service=radarr-svc
      - traefik.http.services.radarr-svc.loadbalancer.server.port=7878
